[package]
name = "gdext-gen"
version = "0.1.0"
edition = "2021"

[package.metadata.docs.rs]
rustdoc-args = ["--document-private-items"]

[dependencies]
serde = { version = "1.0.215", features = ["serde_derive"] }
toml = "0.8.19"
toml_edit = "0.22.22"
